branches:
  only:
  - develop
  - /^release-.*$/
  - /.*-travis$/
  - master

language: python

python: 3.6

os: linux

dist: bionic # Ubuntu 18.04

before_install:
  - sudo apt-get update
  - sudo apt-get -y install gdal-bin
  - sudo apt-get -y install libgdal-dev
  - sudo apt-get -y install openmpi-bin
  - sudo apt-get -y install libopenmpi-dev
  - export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include/gdal
  - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/gdal
  - pip install -U pip
  
install:
  - pip install -r requirements-dev.txt
  - python setup.py install
  - export PYRATEPATH=$(pwd)
  - export PYTHONPATH=$PYRATEPATH:$PYTHONPATH
  - chmod 444 tests/test_data/small_test/tif/geo_070709-070813_unw.tif  # makes the file readonly, used in a test

# command to run tests, e.g. python setup.py test
script:
  - pytest --cov-report term-missing:skip-covered --cov=pyrate tests/

# cache:
#   - apt
#   - pip
#   - $HOME/.cache/pip
