name: Build and deploy documentation to gh-pages
#on:
#  push:
#    branches:
#      - 'master'
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build Html pages
        run: |
          pip install -r requirements-dev.txt
          #          sphinx-build -a docs/ docs/_build/
          cd docs && make html
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/_build/ # The folder the action should deploy.
